# Railway deployment configuration for Google Sheets MCP Server

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uv run mcp-google-sheets"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PORT = "8080"
HOST = "0.0.0.0"
NODE_ENV = "production"
